services:
  wordpress:
    container_name: wordpress_container
    image: localhost:5000/wordpress:6.4.2
    restart: always
    networks:
      - web_network
      - app_network
    # edge handled by nginx
    # ports:
    #   - 8080:80
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ~/ansible_agent/docker_volumes/wordpress:/var/www/html
    depends_on:
      - db

  db:
    container_name: mysql_container
    image: localhost:5000/mysql:8.0
    restart: always
    networks:
      - app_network
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ~/ansible_agent/docker_volumes/mysql:/var/lib/mysql

networks:
  app_network:
  web_network:

volumes:
  wordpress:
  db: