services:
  wordpress:
    image: wordpress
    restart: always
    networks:
      - web_network
      - app_network
    # edge handled by nginx
    # ports:
    #   - 8080:80
    expose:
      - 80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    restart: always
    networks:
      - app_network
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: nginx:1.24.0-alpine3.17-slim
    restart: always
    networks:
      - web_network
    ports:
      - 80:80
    volumes:
      - ../nginx:/etc/nginx/conf.d/

networks:
  app_network:
  web_network:

volumes:
  wordpress:
  db: