---
- name: ensure docker and docker-compose are installed
  become: true
  apt:
    lock_timeout: 300
    name: 
      - docker.io
      - docker-compose
    state: latest
    update_cache: true
    allow_unauthenticated: true
  notify: Restart docker

- name: Added user to docker group
  become: true
  user:
    name: vagrant
    groups: docker

- name: daemon config
  become: true
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '644'
  notify: Restart docker
