- name: Install dependencies + docker itself
  ansible.builtin.apt:
    lock_timeout: 3600
    name:
      - python3-pip
      - docker.io
    state: present
    update_cache: true
    allow_unauthenticated: true
  notify: Restart docker

- name: Update pip
  ansible.builtin.pip:
    name:
      - pip==22.0.4
    state: present

# - name: Install docker
#   ansible.builtin.apt:
#     lock_timeout: 300
#     update_cache: true
#     name: docker.io
#     state: present
#   notify: Restart docker

- name: /etc/docker directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '755'

- name: Daemon.json
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '644'
  notify: Restart docker

- name: Ensure Docker is started and enabled at boot
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker==6.1.3

- name: Install docker-compose
  ansible.builtin.apt:
    lock_timeout: 300
    update_cache: true
    name: docker-compose
    state: present
  notify: Restart docker