- name: Make sure the directory exists
  ansible.builtin.file:
    path: ~/ansible_agent/wordpress
    state: directory
    mode: '0755'

- name: Synchronize the entire directory to the server
  ansible.posix.synchronize:
    src: ./wordpress/
    dest: ~/ansible_agent/wordpress

- name: Make sure containers aren't running
  community.docker.docker_compose:
    project_src: ~/ansible_agent/wordpress/compose
    files:
      - compose.wordpress.yml
    state: absent

- name: Make sure nothing is running on port 80, if it is, give error with process name and exit role
  ansible.builtin.shell: |
    if [[ $(netstat -tulpn | grep 80) ]]; then
      echo "Something is running on port 80, please stop it and try again"
      exit 1
    fi

- name: Create and start Docker Compose containers
  community.docker.docker_compose:
    project_src: /root/ansible_agent/wordpress/compose
    files:
      - compose.wordpress.yml
  register: output

- name: Ensure the containers are running
  community.docker.docker_compose:
    state: present
    project_src: ~/ansible_agent/wordpress/compose/
    files:
      - compose.wordpress.yml
