- name: Make sure the files directory exists
  ansible.builtin.file:
    path: ~/ansible_agent/wordpress/files
    state: directory
    mode: '0644'

- name: Make sure the volumes directory exists
  ansible.builtin.file:
    path: ~/ansible_agent/docker_volumes
    state: directory
    mode: '0664'

- name: copy the files directory to the server
  ansible.builtin.copy:
    src: ../files/
    dest: ~/ansible_agent/wordpress/files
    owner: root
    group: root
    mode: '744'

- name: Make sure containers aren't running
  community.docker.docker_compose:
    project_src: ~/ansible_agent/wordpress/files/compose/
    files:
      - compose.wordpress.yml
    state: absent

- name: Create and start wordpress containers
  community.docker.docker_compose:
    project_name: wp
    state: present
    project_src: ~/ansible_agent/wordpress/files/compose/
    files:
      - compose.wordpress.yml
